services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - back-server

  nginx:
    image: nginx:latest
    container_name: nginxxxxxxx
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - back-server
      

volumes:
  dbdata:
  
  
networks:
  back-server:
    driver: bridge
